const BASE_URL = "https://stattrack.ezxdemo.com/";
//const BASE_URL ="https://stattrack.ezxdemo.com/users/changePassword";
const appLogo = "assets/images/app_logo.png";
const splashBg = "assets/images/splash_bg.png";
const welcomeBg = "assets/images/welcome_bg.png";
const backIcon = "assets/images/backIcon.png";
const backIconWhite = "assets/images/back_white.png";
const navHomeIcon = "assets/images/navHomeIcon.png";
const navTeamIcon = "assets/images/navTeamIcon.png";
const navDashboard = "assets/images/navDashboard.png";
const navProfileIcon = "assets/images/navProfileIcon.png";
const navNotifactionIcon = "assets/images/navNotifactionIcon.png";
const demoImage = "assets/images/demoImage.png";
const sideNavHeader = "assets/images/sideNavHeader.png";
const icHumburger = "assets/images/ichumberger.png";
const sideNavPlanIcon = "assets/images/sideNavPlanIcon.png";
const inviteUser = "assets/images/inviteUser.png";
const logoutIcon = "assets/images/logoutIcon.png";
const topHeaderImg = "assets/images/topHeaderImg.png";
const topHeaderImg2 = "assets/images/topHeaderImg2.png";
const cameraIcon = "assets/images/cameraIcon.png";
const bgImag = "assets/images/bgImag.png";
const nflBallIcon = "assets/images/nflBallIcon.png";
const nflHockey = "assets/images/nflHockey.png";
const nflBaseball = "assets/images/nflBaseball.png";
const forwordIcon = "assets/images/forwordIcon.png";
const teamLogo = "assets/images/teamLogo.png";
const addIcon = "assets/images/addIcon.png";
const demoImage3 = "assets/images/demoImage3.png";
const demoImage4 = "assets/images/demoImage4.png";
const demoImage5 = "assets/images/demo_user_bw.jpg";
const teamIcon = "assets/images/teamIcon.png";
const backgroundIconPayment = "assets/images/backgroundIconPayment.png";
const paytmCircleIcon = "assets/images/paytmCircleIcon.png";
const password_dot = "assets/images/password_dot.png";
const subscription_plan_bg = "assets/images/subscription_plan_bg.png";
const StarIcon = "assets/images/star_icon.png";
const arrowRightIcon = "assets/images/arrow_right.png";
const arrowLeftIcon = "assets/images/arrow_left.png";
const IC_AboutUs = "assets/images/ic_aboutus.png";
const IC_Privacy = "assets/images/ic_privacy.png";
const IC_Term = "assets/images/ic_termcond.png";
const IC_DelUser = "assets/images/ic_deluser.png";

const RAPID_API_KEY =
    "690cab678fmshf73a3e54b201797p14f746jsn4bd3de022654"; //client
//sharedPref
const TeamHomeName = "TeamHomeName";
const TeamAwayName = "TeamAwayName";
const TeamHomeID = "TeamHomeID";
const TeamAwayID = "TeamAwayID";
const PLAYER_RECORD = "PlayerRecord";
const KEY_DASHBOARD_LIST = "KEY_DASHBOARD_LIST";
const SESSION_ID = "46786";
const TOURNAMENT_ID = "9464";

final String StripePublishableKey =
    "pk_test_51Lg86eKVSA5dEldu2Lv0wMKPxoC3qm17ZQW7HEJq61WmTh3O9fNRSqKtyoLmlnWw43uv9UMtwvw8UJ6w1G20yDG300tVvNV6X8";
final String IS_SUBSCRIBE = "IS_SUBSCRIBE";
final String IS_ENABLE = "Enable";
final String IS_DISABLE = "Disable";
