
const String welcome = "Welcome";
const String signUp = "Sign Up";
const String signIn = "Sign In";
const String logIn = "Log In";
const String submit = "Submit";
const String byContinuing = "By Continuing you agree to the ";
const String termAndCondition = "Terms & Conditions";
const String emailAddress = "Email address";
const String password = "Password";
const String welcomeBack = "Welcome Back";
const String forgotPassword = "Forgot password ?";
const String dontHaveAccount = "Don’t have an account? ";
const String createAccount  = "Create Account";
const String firstName  = "First name";
const String lastName  = "Last name";
const String confirmPassword  = "Confirm password";
const String iAgree  = "I Agree to the ";
const String termOfServices  = " Terms of Service";
const String alreadyHaveAccount  = " Already have an account? ";
const String forgotPassword2  = "Forgot Password";
const String changePassword  = "Change password";
const String currentPassword  = "Current password";
const String newPassword  = "New password";
const String confirmNewPassword  = "Confirm new password";
const String home = "Home";
const String team = "Team";
const String dashboard = "Dashboard";
const String profile = "Profile";
const String notifaction = "Notification";
const String myPlan = "My plan";
const String invitePeople = "Invite people";
const String logout = "Logout";
const String AboutUs = "About Us";
const String PrivacyPolicy = "Privacy Policy";
const String TermsNCond = "Terms & Condition";
const String DeleteAccount = "Delete Account";


